import * as React from 'react';

export default function SummaryTableHeader() {
    return (
        <thead>
            <tr>
                <th
                    data-col="file"
                    data-fmt="html"
                    data-html="true"
                    class="file"
                >
                    File
                </th>
                <th
                    data-col="pic"
                    data-type="number"
                    data-fmt="html"
                    data-html="true"
                    class="pic"
                />
                <th
                    data-col="statements"
                    data-type="number"
                    data-fmt="pct"
                    class="pct"
                >
                    Statements
                </th>
                <th
                    data-col="statements_raw"
                    data-type="number"
                    data-fmt="html"
                    class="abs"
                />
                <th
                    data-col="branches"
                    data-type="number"
                    data-fmt="pct"
                    class="pct"
                >
                    Branches
                </th>
                <th
                    data-col="branches_raw"
                    data-type="number"
                    data-fmt="html"
                    class="abs"
                />
                <th
                    data-col="functions"
                    data-type="number"
                    data-fmt="pct"
                    class="pct"
                >
                    Functions
                </th>
                <th
                    data-col="functions_raw"
                    data-type="number"
                    data-fmt="html"
                    class="abs"
                />
                <th
                    data-col="lines"
                    data-type="number"
                    data-fmt="pct"
                    class="pct"
                >
                    Lines
                </th>
                <th
                    data-col="lines_raw"
                    data-type="number"
                    data-fmt="html"
                    class="abs"
                />
            </tr>
        </thead>
    );
}
